@startuml

entity Customer {
  + ID (PK)
  UserID INT
  Document VARCHAR(255)
  Name VARCHAR(255)
  Email VARCHAR(255)
  Password VARCHAR(255)
}

entity User {
  + ID (PK)
  Login VARCHAR(255)
  Password VARCHAR(255)
  AccessLevelID INT
  CreatedAt TIMESTAMP WITH TIME ZONE
}

entity Access {
  + ID (PK)
  AccessLevelID INT
  USERID VARCHAR(255)
  METADATA VARCHAR(255)
  AccessAt TIMESTAMP WITH TIME ZONE
}

entity AccessLevel {
  + ID (PK)
  LEVEL VARCHAR(10)
}

Customer --|{ User : "UserID"
Access --|{ User : "UserID"
AccessLevel --|{ Access : "AccessLevelID"

@enduml
