customerServer:
  port: 8081
userServer:
  port: 8082

port: 8083
db:
  connectionString: host=127.0.0.1 port=5432 dbname=fiap_tech_challenge user=postgres password=1234 sslmode=disable

user_tech
tech_challenge_user_password