name: pull_request_workflow
on:
  pull_request:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: CGO_ENABLED=0 go build -v -o dist/user-service cmd/user-service/main.go
      - name: Test
        run: go test -v ./... -coverprofile="c.out"
  sonarqube:
    name: sonarqube 
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep --config auto .
      - run: semgrep scan || true
